nome= str(input("qual seu nome??: "))
maiusculo= nome.upper()
minusculo= nome.lower()
letras = len(nome)
qntsletras = len(nome[0])
print(maiusculo)
print(minusculo)
print(letras)
print(qntsletras)