n= input("digite um valor: ")
print(type(n))
print("é um numero? ",n.isnumeric())
print("é uma letra? ",n.isalpha())
print("tem espaço? ",n.isspace())
print("é minusculo? ",n.islower())
print("é maiusculo? ", n.isupper())